### ISSUE TITLE
could not surpass undelegate call

### ISSUE THREAD

**Issue by aion-chris** [aionnetwork/protocol_contracts#3]
ubuntu 18.04, Aion(R)/v0.2.6-1.994c15f/x86_64-linux-gnu/rustc-1.28.0
----------------------------------------------------------------------------------------------------------------
Exception throws at 
https://github.com/aionnetwork/protocol_contracts/blob/master/pool-registry/src/main/java/org/aion/unity/PoolRegistry.java#L223

![image](https://user-images.githubusercontent.com/40782546/65234961-37914780-db08-11e9-92d4-8634483802b8.png)

![image](https://user-images.githubusercontent.com/40782546/65235119-95259400-db08-11e9-8834-a70417c9e9ab.png)

**Comment by aion-shidokht** [comment]
Closing the issue since this is caused if the `PoolRegistry` contract was deployed with an incorrect `StakerRegistry` address.
